import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google' // Import Google Fonts
import localFont from 'next/font/local' // Import local Fonts
import NavBar from './NavBar'
import AuthProvider from './auth/Provider'
// import GoogleAnalyticsScript from './GoogleAnaliticsScript'

// create a fonst
const inter = Inter({ subsets: ['latin'] })

// create a fonst
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500']
})

// create local font
const poppins = localFont({
  src: '../public/fonts/poppins-regular-webfont.woff2',
  variable: '--font-poppins'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: { // Share our pages on social media platforms
    title: '...',
    description: '...'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="winter">
      {/* <GoogleAnalyticsScript /> */} {/* Third-Party component */}
      {/* <body className={poppins.className}> Set roboto font with Google or poppins whith local font */}
      <body className={poppins.variable}> {/* Set roboto font with Google or poppins whith local font */}
        <AuthProvider>
          <NavBar />
          <main className='p-5'>
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  )
}
